# Generated by Django 6.0 on 2026-01-25 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit (e.g., PROD-001, ABC-123)', max_length=100, unique=True, verbose_name='SKU')),
                ('title', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, help_text='Product model/number', max_length=100, verbose_name='Model Number')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, verbose_name='Full Description')),
                ('specification', models.TextField(blank=True, verbose_name='Specifications')),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='Purchase cost', max_digits=10, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Retail price', max_digits=10, verbose_name='Selling Price')),
                ('is_new', models.BooleanField(default=True, verbose_name='Mark as New')),
                ('thumbnail_image', models.ImageField(upload_to='products/thumbnails/%Y/%m/', verbose_name='Main Image')),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/small/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='draft', max_length=20, verbose_name='Status')),
                ('stock_availability', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre Order'), ('coming_soon', 'Coming Soon')], default='in_stock', max_length=20, verbose_name='Stock Status')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Meta Keywords')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Product')),
                ('best_seller', models.BooleanField(default=False, verbose_name='Best Seller')),
                ('trending', models.BooleanField(default=False, verbose_name='Trending')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (e.g., 10.00 for 10%)', max_digits=5)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount (e.g., 5.00 for $5 off)', max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='backend.product')),
            ],
            options={
                'verbose_name': 'Product Discount',
                'verbose_name_plural': 'Product Discounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/%Y/%m/%d/')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='products/images/small/%Y/%m/%d/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for SEO', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['position', '-is_primary'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='backend_pro_sku_69bd38_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='backend_pro_slug_7b9548_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'published_at'], name='backend_pro_status_f79c00_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='backend_pro_categor_d43ed9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'position')},
        ),
    ]
