# Generated by Django 6.0 on 2026-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_product_productdiscount_productimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('discontinued', 'Discontinued')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
