# Generated by Django 6.0 on 2026-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_product_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_small',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.ImageField(help_text='Primary product image (required)', upload_to='products/thumbnails/%Y/%m/', verbose_name='Main Image'),
        ),
    ]
