# Generated by Django 6.0 on 2026-01-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_product_thumbnail_small_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False, verbose_name='New'),
        ),
    ]
