# Generated by Django 6.0 on 2026-01-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_product_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
    ]
