# Generated by Django 6.0 on 2026-01-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_product_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='start_date',
            field=models.DateField(),
        ),
    ]
