# Generated by Django 6.0 on 2026-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_deliverycharge_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycharge',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverycharge',
            name='thana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
