# Generated by Django 6.0 on 2026-03-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_deliverycharge_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='thana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
