# Generated by Django 6.0 on 2026-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_order_thana'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ekka', max_length=150)),
                ('footer_tagline', models.CharField(blank=True, default='Your trusted destination for quality products.', max_length=255)),
                ('footer_copyright', models.CharField(blank=True, default='All rights reserved.', max_length=255)),
                ('about_page_title', models.CharField(default='About Us', max_length=150)),
                ('about_section_title', models.CharField(default='About Us', max_length=150)),
                ('about_subtitle', models.CharField(blank=True, default='About our business', max_length=255)),
                ('about_heading', models.CharField(default='Who we are', max_length=255)),
                ('about_description', models.TextField(blank=True, default='Tell customers about your company, your products, and what makes your brand different.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('contact_page_title', models.CharField(default='Contact Us', max_length=150)),
                ('contact_heading', models.CharField(default='Contact us', max_length=150)),
                ('contact_subtitle', models.CharField(blank=True, default='We would love to hear from you.', max_length=255)),
                ('contact_address', models.TextField(blank=True, default='Add your business address here.')),
                ('contact_phone', models.CharField(blank=True, default='+880', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='support@example.com', max_length=254)),
                ('contact_map_embed_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
