# Generated by Django 6.0 on 2026-03-11 15:36

from django.db import migrations, models


def migrate_site_content(apps, schema_editor):
    SiteContent = apps.get_model('backend', 'SiteContent')
    SiteBranding = apps.get_model('backend', 'SiteBranding')
    AboutPage = apps.get_model('backend', 'AboutPage')
    ContactPage = apps.get_model('backend', 'ContactPage')

    old = SiteContent.objects.order_by('pk').first()
    if not old:
        return

    SiteBranding.objects.update_or_create(
        pk=1,
        defaults={
            'site_name': old.site_name,
            'footer_tagline': old.footer_tagline,
            'footer_copyright': old.footer_copyright,
        },
    )
    AboutPage.objects.update_or_create(
        pk=1,
        defaults={
            'page_title': old.about_page_title,
            'section_title': old.about_section_title,
            'subtitle': old.about_subtitle,
            'heading': old.about_heading,
            'description': old.about_description,
            'image': old.about_image,
        },
    )
    ContactPage.objects.update_or_create(
        pk=1,
        defaults={
            'page_title': old.contact_page_title,
            'heading': old.contact_heading,
            'subtitle': old.contact_subtitle,
            'address': old.contact_address,
            'phone': old.contact_phone,
            'email': old.contact_email,
            'map_embed_url': old.contact_map_embed_url,
            'facebook_url': old.facebook_url,
            'instagram_url': old.instagram_url,
            'twitter_url': old.twitter_url,
            'linkedin_url': old.linkedin_url,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ekka', max_length=150)),
                ('footer_tagline', models.CharField(blank=True, default='Your trusted destination for quality products.', max_length=255)),
                ('footer_copyright', models.CharField(blank=True, default='All rights reserved.', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('dark_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('dark_footer_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='About Us', max_length=150)),
                ('section_title', models.CharField(default='About Us', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='About our business', max_length=255)),
                ('heading', models.CharField(default='Who we are', max_length=255)),
                ('description', models.TextField(blank=True, default='Tell customers about your company, your products, and what makes your brand different.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Contact Us', max_length=150)),
                ('heading', models.CharField(default='Contact us', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='We would love to hear from you.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True, default='Add your business address here.')),
                ('phone', models.CharField(blank=True, default='+880', max_length=50)),
                ('email', models.EmailField(blank=True, default='support@example.com', max_length=254)),
                ('map_embed_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Us Page',
                'verbose_name_plural': 'Contact Us Page',
            },
        ),
        migrations.RunPython(migrate_site_content, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SiteContent',
        ),
    ]
